/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM_all.h"
#include "Clock_1.h"
#include "Pin_PWM2_ava_aliases.h"
#include "Pin_PWM2_ava.h"
#include "Pin_INa2_ava_aliases.h"
#include "Pin_INa2_ava.h"
#include "Pin_INb2_ava_aliases.h"
#include "Pin_INb2_ava.h"
#include "Pin_INa1_ava_aliases.h"
#include "Pin_INa1_ava.h"
#include "Pin_INb1_ava_aliases.h"
#include "Pin_INb1_ava.h"
#include "Pin_INa3_arr_aliases.h"
#include "Pin_INa3_arr.h"
#include "Pin_INb3_arr_aliases.h"
#include "Pin_INb3_arr.h"
#include "Pin_INa4_arr_aliases.h"
#include "Pin_INa4_arr.h"
#include "Pin_INb4_arr_aliases.h"
#include "Pin_INb4_arr.h"
#include "ADC_Pot.h"
#include "Pot_analog_aliases.h"
#include "Pot_analog.h"
#include "Pin_PWM3_arr_aliases.h"
#include "Pin_PWM3_arr.h"
#include "Pin_PWM1_ava_aliases.h"
#include "Pin_PWM1_ava.h"
#include "Pin_PWM4_arr_aliases.h"
#include "Pin_PWM4_arr.h"
#include "Wheel_Modes.h"
#include "ADC_Pot_IRQ.h"
#include "ADC_Pot_theACLK.h"
#include "ADC_Pot_Bypass_aliases.h"
#include "ADC_Pot_Bypass.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

